version: "3.7"

# See https://stackoverflow.com/questions/29261811/use-docker-compose-env-variable-in-dockerbuild-file
services:

  webui:
    build:
      context: ./webui
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_DIVISION: ${IMAGE_REPOSITORY_DIVISION}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-webui-dev
    privileged: true    
    security_opt:
      - no-new-privileges:true     
    ports:
      - "8081:3001"
    volumes:
      - ./webui:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPULLING=true
    networks:
      - gateway-dev    

  grid:
    build:
      context: ./grid
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_DIVISION: ${IMAGE_REPOSITORY_DIVISION}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-grid-dev
    privileged: true    
    security_opt:
      - no-new-privileges:true     
    ports:
      - "8082:3002"
    volumes:
      - ./grid:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPULLING=true
    networks:
      - gateway-dev         

  cards:
    build:
      context: ./cards
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_DIVISION: ${IMAGE_REPOSITORY_DIVISION}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-cards-dev
    privileged: true    
    security_opt:
      - no-new-privileges:true     
    ports:
      - "8083:3003"
    volumes:
      - ./grid:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPULLING=true
    networks:
      - gateway-dev

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.dev
      args: # from env_file
        IMAGE_REPOSITORY: ${IMAGE_REPOSITORY}
        IMAGE_REPOSITORY_DIVISION: ${IMAGE_REPOSITORY_DIVISION}
        PROXY_USER: ${PROXY_USER}
        PROXY_PASSWORD: ${PROXY_PASSWORD}
        PROXY_FQDN: ${PROXY_FQDN}
        PROXY_PORT: ${PROXY_PORT}
    env_file:
      - .env
    container_name: ${UNIQUE_NAMESPACE}-gateway-dev
    depends_on:
      - webui
    privileged: true
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./gateway:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPULLING=true
    networks:
      - default
      - gateway-dev
    external_links:
      - agility-game-knowledge-webui-dev
      - agility-game-knowledge-grid-dev
      - agility-game-knowledge-cards-dev

# see https://stackoverflow.com/questions/45255066/create-networks-automatically-in-docker-compose
networks:
  gateway-dev:
    external: true
    name: gateway-dev
